name: matensemble
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.12
  - pip
  - flux-core
  - flux-sched
  - mpich
  - mpi=*=mpich
  - mpi4py
  - lammps
  - pip:
      - matensemble
