FROM nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
ARG DEBIAN_FRONTEND=noninteractive

COPY --from=ghcr.io/astral-sh/uv:0.11.8 /uv /uvx /bin/
ENV VIRTUAL_ENV=/opt/basic
RUN uv venv $VIRTUAL_ENV --seed --python 3.12
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /opt

RUN apt-get update && apt-get install --yes \
    build-essential gfortran wget \
    && apt-get clean

ARG mpich=4.1.2
ARG mpich_prefix=mpich-$mpich
RUN wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xvzf $mpich_prefix.tar.gz                                           && \
    cd $mpich_prefix                                                        && \
    ./configure                                                             && \
    make -j 16                                                              && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf $mpich_prefix
RUN /sbin/ldconfig

ARG mpi4py=4.0.3
RUN python -m pip install mpi4py==$mpi4py cupy-cuda12x
