name: matensemble
channels:
  - https://conda.ovito.org
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ovito=3.12.1
  - gcc=12.2.0
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0 
  - matplotlib>=3.4.0
  - flux-core=0.64.0
  - flux-sched=0.38.0
  - redis>=4.0.0
  - cython>=0.29.0


