FROM savannah.ornl.gov/olcf-container-images/cpe:25.03_gnu_ubuntu 

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt


# System packages
RUN apt-get update && apt-get install -y --no-install-recommends               \
    build-essential autoconf automake bash ca-certificates curl git wget unzip \
    build-essential gfortran pkg-config ninja-build cmake libblas-dev libtool  \
    liblapack-dev libgsl-dev libfftw3-dev libopenblas-dev libhdf5-dev          \
    libsqlite3-dev libarchive-dev libcurl4-openssl-dev libzmq3-dev libtool-bin \
    libsodium-dev libjansson-dev libczmq-dev libyaml-cpp-dev libedit-dev       \
    libboost-all-dev uuid-dev lua5.3 liblua5.3-dev python3-venv python3-dev    \
    && rm -rf /var/lib/apt/lists/*


# Python env
RUN python3 -m venv /opt/basic && \
    ln -sf /opt/basic/bin/pip /usr/local/bin/pip
ENV PATH=/opt/basic/bin:$PATH
ENV VIRTUAL_ENV=/opt/basic
ENV PIP_CONFIG_FILE=/dev/null
ENV PIP_REQUIRE_HASHES=0
ENV PIP_CONSTRAINT=
ENV PIP_REQUIREMENT=
ENV CONSTRAINT=
ENV REQUIREMENT=

RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel cffi \
    PyYAML cython pyarrow pyfftw tqdm papermill py3Dmol ply pyyaml


# Build mpim4py
RUN MPICC="hipcc -L${MPICH_DIR}/lib -lmpi ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a} -I${MPICH_DIR}/include" pip install --no-cache-dir --no-binary=mpi4py mpi4py


# Flux & Fluxion Build
WORKDIR /opt

RUN git clone -b v0.70.0 https://github.com/flux-framework/flux-core.git && \
    cd flux-core                                                         && \
    PYTHON=/opt/basic/bin/python ./autogen.sh                            && \
    ./configure                                                          && \
    make -j16                                                            && \
    make install                                                         && \
    ldconfig

RUN git clone -b v0.41.0 https://github.com/flux-framework/flux-sched.git && \
    cd flux-sched                                                         && \
    cmake -B build                                                        && \
    cmake --build build -j 16                                             && \
    cmake --build build -t install                                        && \
    ldconfig

RUN python -m pip install --no-cache-dir flux-python==0.70.0
ENV LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}

# build symmetrix and then lammps with symmetrix support
RUN git clone --recursive https://github.com/wcwitt/symmetrix && \
    cd symmetrix && \
    git checkout daeda1c1cf5eee633c3f3f409b6bba327f29b4b7 && \
    cd symmetrix && \
    pip install .


# build lammps
WORKDIR /opt
ENV LINKFLAGS="-L${MPICH_DIR}/lib -lmpi"
RUN wget https://github.com/lammps/lammps/archive/refs/tags/stable_22Jul2025_update3.tar.gz && \
    tar -xzvf stable_22Jul2025_update3.tar.gz && \
    rm -rf stable_22Jul2025_update3.tar.gz    && \
    mv lammps-stable_22Jul2025_update3 lammps && \
    mkdir -p /opt/lammps/build

# patch lammps to use pair_style symmetrix
WORKDIR /opt/symmetrix/pair_symmetrix
RUN    ./install.sh /opt/lammps

WORKDIR /opt/lammps/build

ENV LMP_MACH=frontier_gfx90a
ENV FLAGS='-fdenormal-fp-math=ieee -fgpu-flush-denormals-to-zero -munsafe-fp-atomics -I${MPICH_DIR}/include'
ENV LINKFLAGS="-L${MPICH_DIR}/lib -lmpi ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}"
ENV MPICH_GPU_SUPPORT_ENABLED=1

RUN cmake ../cmake \
    -D CMAKE_INSTALL_PREFIX=${INSTDIR:-$PWD/install} \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_SHARED_LIBS=ON \
    -D BUILD_MPI=ON \
    -D CMAKE_CXX_COMPILER=${ROCM_PATH}/bin/hipcc \
    -D CMAKE_CXX_STANDARD=20 \
    -D CMAKE_CXX_STANDARD_REQUIRED=ON \
    -D CMAKE_CXX_SCAN_FOR_MODULES=OFF \
    -D CMAKE_CXX_FLAGS="-fdenormal-fp-math=ieee -fgpu-flush-denormals-to-zero -munsafe-fp-atomics -D__HIP_PLATFORM_AMD__=1" \
    -D KokkosKernels_ENABLE_ETI=OFF \
    -D KokkosKernels_INST_DOUBLE=OFF \
    -D KokkosKernels_INST_LAYOUTLEFT=OFF \
    -D CMAKE_EXE_LINKER_FLAGS="-lmpi" \
    -D CMAKE_SHARED_LINKER_FLAGS="" \
    -D PKG_KOKKOS=ON \
    -D Kokkos_ENABLE_HIP=ON \
    -D Kokkos_ARCH_VEGA90A=ON \
    -D Kokkos_ARCH_ZEN3=ON \
    -D Kokkos_ENABLE_SERIAL=ON \
    -D Kokkos_ENABLE_OPENMP=ON \
    -D Kokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=ON \
    -D Kokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON \
    -D SYMMETRIX_KOKKOS=ON \
    -D BUILD_OMP=ON \
    -D FFT=FFTW3 \
    -D BLAS_LIBRARIES="${LIBSCI_PATH}" \
    -D LAPACK_LIBRARIES="${LIBSCI_PATH}" \
    -D PYTHON_EXECUTABLE=$(which python) \
    -D PKG_MANYBODY=ON \
    -D PKG_MOLECULE=ON \
    -D PKG_KSPACE=ON \
    -D PKG_RIGID=ON \
    -D PKG_REAXFF=ON \
    -D PKG_REPLICA=ON \
    -D PKG_ML-SNAP=ON \
    -D PKG_ML-IAP=ON \
    -D PKG_ML-PACE=ON \
    -D PKG_SPIN=ON \
    -D PKG_PYTHON=ON \
    -D MLIAP_ENABLE_PYTHON=ON



RUN make -j 16      && \
    make install    && \
    make install-python
ENV PATH=/opt/lammps/install/bin:${PATH}


# install ovito
RUN apt update && apt install -y \
    freeglut3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libglew-dev \
    mesa-utils

RUN pip uninstall -y ovito && \
    pip install -U ovito

RUN python -c "import ovito; print('ovito installation ok')"


#------------------ LAMMPS RELATED FLAGS (e.g., FOR KOKKOS)
ENV OMP_PROC_BIND=spread
ENV OMP_PLACES=threads
ENV HIP_VISIBLE_DEVICES=$ROCR_VISIBLE_DEVICES
# Fixes the HIPManagedSpace warning
ENV HSA_XNACK=1 
# Fixes the MPICH GPU-aware MPI warning you saw in the log
ENV MPICH_GPU_SUPPORT_ENABLED=1
ENV SLURM_GPUS_PER_NODE=8

# tests
RUN python -c "import mpi4py; print('python stack ok')" && \
    python -c "import lammps; print('lammps python ok')"                                                  && \
    rm -rf /usr/local/cuda/lib64/stubs && find /usr/local -path '*/lib/stubs' -type d -prune -exec rm -rf {} +
