FROM docker.io/nersc/base_gpu:25.11

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

# System packages
RUN apt-get update && apt-get install -y --no-install-recommends               \
    bash ca-certificates curl git wget unzip build-essential gfortran          \
    pkg-config ninja-build cmake libblas-dev liblapack-dev libgsl-dev          \
    libfftw3-dev libopenblas-dev libhdf5-dev libsqlite3-dev libarchive-dev     \
    libcurl4-openssl-dev libzmq3-dev libsodium-dev libjansson-dev libczmq-dev  \
    libyaml-cpp-dev libedit-dev libboost-all-dev uuid-dev lua5.3 liblua5.3-dev \
    python3 python3-venv python3-dev                                           \
    && rm -rf /var/lib/apt/lists/*

# Python env
RUN python3 -m venv /opt/basic && \
    ln -sf /opt/basic/bin/pip /usr/local/bin/pip
ENV PATH=/opt/basic/bin:$PATH
ENV VIRTUAL_ENV=/opt/basic
ENV PIP_CONFIG_FILE=/dev/null
ENV PIP_REQUIRE_HASHES=0
ENV PIP_CONSTRAINT=
ENV PIP_REQUIREMENT=
ENV CONSTRAINT=
ENV REQUIREMENT=

RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel cffi

RUN env                                  \
    -u PIP_CONSTRAINT                    \
    -u PIP_BUILD_CONSTRAINT              \
    -u PIP_REQUIREMENT                   \
    -u PIP_REQUIRE_HASHES                \
    -u CONSTRAINT                        \
    -u REQUIREMENT                       \
    PIP_CONFIG_FILE=/dev/null            \
    python -m pip install --no-cache-dir \
      "numpy==2.0.0"                     \
      "pandas>=1.3.0"                    \
      "scipy>=1.7.0"                     \
      "pymatgen>=2022.0.0"               \
      "ase>=3.22.0"                      \
      "scikit-learn>=1.0.0"              \
      "matplotlib>=3.4.0"                \
      "seaborn>=0.11.0"                  \
      "botorch==0.13.0"                  \
      "imageio>=2.9.0"                   \
      cython pyarrow pyfftw tqdm papermill py3Dmol ply pyyaml

RUN PIP_REQUIRE_HASHES=0 python -m pip install --no-cache-dir "b2[full]"

# GPU python stack
RUN python -m pip install --no-cache-dir                     \
    --extra-index-url https://download.pytorch.org/whl/cu124 \
    "torch==2.5.0+cu124"                                     \
    "cupy-cuda12x==13.5.1"                                   \
    "cuequivariance==0.6.0"                                  \
    "cuequivariance-torch==0.6.0"                            \
    "cuequivariance-ops-torch-cu12==0.3.0"                   \
    mace-torch==0.3.14



# Build MPICH and install mpi4py
ARG mpich=3.4.3
ARG mpich_prefix=mpich-$mpich

WORKDIR /opt
RUN wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xvzf $mpich_prefix.tar.gz                                           && \
    cd $mpich_prefix                                                        && \
    FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch ./configure --with-device=ch4:ofi && \
    make -j 4                                                               && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf $mpich_prefix
RUN /sbin/ldconfig

RUN MPICC="cc -shared" python -m pip install --no-cache-dir --force-reinstall --no-binary=mpi4py mpi4py==4.0.3


#Install HWLOC
WORKDIR /opt
RUN git clone -b v2.11 https://github.com/open-mpi/hwloc.git hwloc && \
    cd hwloc                                                       && \
    ./autogen.sh                                                   && \
    ./configure                                                    && \
    make -j 16                                                     && \
    make install


# ----------
# Flux build
# ----------
WORKDIR /opt

RUN git clone -b v0.70.0 https://github.com/flux-framework/flux-core.git && \
    cd flux-core                                                         && \
    ./autogen.sh                                                         && \
    ./configure                                                          && \
    make -j 16                                                           && \
    make install                                                         && \
    ldconfig

RUN git clone -b v0.41.0 https://github.com/flux-framework/flux-sched.git && \
    cd flux-sched                                                         && \
    cmake -B build                                                        && \
    cmake --build build -j 16                                             && \
    cmake --build build -t install                                        && \
    ldconfig

RUN python -m pip install --no-cache-dir flux-python==0.70.0
ENV LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}


# Install MPI-ping-pong from OLCF
WORKDIR /opt
ENV MPI_HOME "/opt/mpich/install"
RUN git clone https://github.com/olcf-tutorials/MPI_ping_pong.git test_code
RUN cd /opt/test_code/cpu                                                   && \
    make
RUN cd /opt/test_code/cuda_staged                                           && \
    sed -i 's:-arch=sm_70:-arch=sm_80:g' Makefile                           && \
    sed -i 's:OMPI_DIR:MPI_HOME:g' Makefile                                 && \
    sed -i 's:-lmpi_ibm:-lmpi:g' Makefile                                   && \
    make
RUN cd /opt/test_code/cuda_aware                                            && \
    sed -i 's:-arch=sm_70:-arch=sm_80:g' Makefile                           && \
    sed -i 's:OMPI_DIR:MPI_HOME:g' Makefile                                 && \
    sed -i 's:-lmpi_ibm:-lmpi:g' Makefile                                   && \
    make
ENV PATH=$PATH:/opt/test_code/cpu
ENV PATH=$PATH:/opt/test_code/cuda_staged
ENV PATH=$PATH:/opt/test_code/cuda_aware

ENV PATH=$PATH:/opt/lammps/build/plumed_build-prefix/bin
ENV PATH=$PATH:/opt/lammps/build/plumed_build-prefix/include
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/lammps/build/plumed_build-prefix/lib
ENV PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lammps/build/plumed_build-prefix/lib/pkgconfig
ENV PLUMED_KERNEL=/opt/lammps/build/plumed_build-prefix/lib/libplumedKernel.so
ARG BLAS_LIBRARIES=/usr/local/blas/lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/fftw/install/lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/blas
ENV PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/fftw


# ------------
# LAMMPS build
# ------------
WORKDIR /opt
RUN git clone https://github.com/brucefan1983/NEP_CPU.git nep_cpu                           && \
    cp -r /opt/nep_cpu/src/* /opt/nep_cpu/interface/lammps/USER-NEP                         && \
    wget https://github.com/lammps/lammps/archive/refs/tags/stable_22Jul2025_update3.tar.gz && \
    tar -xzvf stable_22Jul2025_update3.tar.gz                                               && \
    rm -rf stable_22Jul2025_update3.tar.gz                                                  && \
    mv lammps-stable_22Jul2025_update3 lammps                                               && \
    mkdir -p /opt/lammps/build                                                              && \
    cp -r /opt/nep_cpu/interface/lammps/USER-NEP /opt/lammps/src                            && \
    sed -i 's/F95FLAGS += /F90FLAGS += /' /opt/lammps/cmake/Modules/Packages/ML-QUIP.cmake
ENV NVCC_WRAPPER_DEFAULT_ARCH=sm_80
ENV OMPI_CXX=/opt/lammps/lib/kokkos/bin/nvcc_wrapper
WORKDIR /opt/lammps/build
RUN sed -i 's/^default_arch="sm_70"/default_arch="sm_80"/' /opt/lammps/lib/kokkos/bin/nvcc_wrapper
RUN cmake                                                            \
      -D CMAKE_INSTALL_PREFIX=/opt/lammps/install                    \
      -D CMAKE_BUILD_TYPE=Release                                    \
      -D CMAKE_CXX_COMPILER=/opt/lammps/lib/kokkos/bin/nvcc_wrapper  \
      -D CMAKE_CXX_STANDARD=17                                       \
      -D CMAKE_POSITION_INDEPENDENT_CODE=ON                          \
      -D CMAKE_CUDA_ARCHITECTURES=80                                 \
      -D CMAKE_POSITION_INDEPENDENT_CODE=ON                          \
      -D CMAKE_EXE_FLAGS="-dynamic"                                  \
      -D BUILD_MPI=ON                                                \
      -D BUILD_SHARED_LIBS=ON                                        \
      -D LAMMPS_EXCEPTIONS=ON                                        \
      -D LAMMPS_SIZES=BIGBIG                                         \
      -D Kokkos_ARCH_ZEN3=YES                                        \
      -D Kokkos_ARCH_AMPERE80=ON                                     \
      -D Kokkos_ENABLE_CUDA=YES                                      \
      -D Kokkos_ENABLE_OPENMP=YES                                    \
      -D PKG_KOKKOS=YES                                              \
      -D PKG_MANYBODY=ON                                             \
      -D PKG_MOLECULE=ON                                             \
      -D PKG_REPLICA=ON                                              \
      -D GPU_API=CUDA                                                \
      -D GPU_ARCH=sm_80                                              \
      -D PKG_BODY=ON                                                 \
      -D PKG_INTERLAYER=ON                                           \
      -D PKG_MC=ON                                                   \
      -D PKG_QEQ=ON                                                  \
      -D PKG_RIGID=ON                                                \
      -D PKG_SPIN=YES                                                \
      -D PKG_REAXFF=ON                                               \
      -D PKG_PYTHON=YES                                              \
      -D PKG_ML-SNAP=YES                                             \
      -D PKG_ML-IAP=YES                                              \
      -D PKG_ML-PACE=YES                                             \
      -D MLIAP_ENABLE_PYTHON=YES                                     \
      -D DOWNLOAD_PLUMED=YES                                         \
      -D DOWNLOAD_MSCG=YES                                           \
      -D DOWNLOAD_SCAFACOS=YES                                       \
      -D DOWNLOAD_QUIP=YES                                           \
      -D DOWNLOAD_KIM=YES                                            \
      -D DOWNLOAD_EIGEN3=YES                                         \
      -D DOWNLOAD_LATTE=YES                                          \
      -D PLUMED_MODE=STATIC                                          \
      ../cmake
RUN make -j 16          && \
    make install        && \
    make install-python
ENV PATH=/opt/lammps/install/bin:${PATH}

# tests
RUN python -c "import numpy, pandas, scipy, ase, pymatgen, torch, cupy, mpi4py; print('python stack ok')" && \
    python -c "import lammps; print('lammps python ok')"                                                  && \
    rm -rf /usr/local/cuda/lib64/stubs && find /usr/local -path '*/lib/stubs' -type d -prune -exec rm -rf {} +

# Remove CUDA stub libraries to fix runtime GPU detection
ENV LD_LIBRARY_PATH=/opt/lammps/install/lib:/opt/fftw/install/lib:/opt/hdf5/install/lib:/usr/local/lib:/usr/lib64:/usr/lib
WORKDIR /opt
