FROM docker.io/ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf automake libtool make pkg-config libc6-dev libzmq3-dev uuid-dev \
    libjansson-dev liblz4-dev libarchive-dev libhwloc-dev libsqlite3-dev \
    lua5.1 liblua5.1-dev lua-posix python3 python3-dev python3-cffi \
    python3-ply python3-setuptools python3-yaml python3-sphinx aspell \
    aspell-en time valgrind mpich libmpich-dev jq libboost-dev \
    libboost-graph-dev libedit-dev libyaml-cpp-dev git curl ca-certificates \
    build-essential wget ninja-build cmake python3-venv python3-pip \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*
    
RUN git config --global http.sslVerify false

RUN python3 -m venv /opt/basic && \
    ln -sf /opt/basic/bin/pip /usr/local/bin/pip
ENV PATH=/opt/basic/bin:$PATH

RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel cffi \
    PyYAML cython pyarrow pyfftw tqdm papermill py3Dmol ply pyyaml sphinx

RUN MPICC=mpicc python -m pip install --no-cache-dir --force-reinstall --no-binary=mpi4py mpi4py

# Flux & Fluxion Build
WORKDIR /opt
RUN git clone -b v0.70.0 https://github.com/flux-framework/flux-core.git && \
    cd flux-core                                                         && \
    PYTHON=/opt/basic/bin/python ./autogen.sh                            && \
    ./configure                                                          && \
    make -j8                                                             && \
    make install                                                         && \
    ldconfig

RUN git clone -b v0.41.0 https://github.com/flux-framework/flux-sched.git && \
    cd flux-sched                                                         && \
    cmake -B build                                                        && \
    cmake --build build -j1                                               && \
    cmake --build build -t install                                        && \
    ldconfig

RUN python -m pip install --no-cache-dir flux-python==0.70.0
ENV LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH:-}
