FROM nersc/lammps_flux:26.03

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl    git    gcc

# install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh; \
    export PATH="/usr/local/bin:${PATH}"; \
    uv --version

# setup uv to install deps to /opt/venv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv

# clone MatEnsemble
RUN set -euo pipefail; \
    mkdir -p /opt/src; \
    cd /opt/src; \
    rm -rf MatEnsemble; \
    git clone --depth 1 https://github.com/FredDude2004/MatEnsemble.git; \
    cd MatEnsemble; \
    uv export --format requirements.txt --output-file requirements.txt; \ 
    uv pip install -r requirements.txt

ENV PATH="/opt/venv/bin:${PATH}"

