"""
MatEnsemble campaign: lammps_ovito_coordination_perlmutter_2026-06-11

Science goal:
Run a short LAMMPS Lennard-Jones NVT simulation from a randomized 3D atom box,
write trajectory.lammpstrj, then hand that file to a standalone OVITO Python
Reference API analysis chore that computes per-particle coordination numbers
over time and renders a 3D image frame.

This workflow is intentionally small and dependency-driven:
1. LAMMPS generates the trajectory.
2. OVITO consumes the trajectory through a MatEnsemble output reference.

Generated by the MatEnsemble MCP server. Review the chore bodies, container
image, and resource requests before launching on an allocation.
"""

from __future__ import annotations

import csv
import subprocess
import sys
import textwrap
from pathlib import Path

from matensemble.pipeline import Pipeline

pipe = Pipeline()


@pipe.chore(name="run_lammps_lj_nvt", num_tasks=1, cores_per_task=1, gpus_per_task=0)
def run_lammps_lj_nvt() -> dict:
    """Build a random Lennard-Jones system, relax overlaps, and write a trajectory."""

    from lammps import lammps

    workdir = Path.cwd()
    trajectory_path = workdir / "trajectory.lammpstrj"

    cmdargs = [
        "-screen",
        "none",
        "-log",
        "none",
    ]

    commands = [
        "units lj",
        "atom_style atomic",
        "boundary p p p",
        "lattice fcc 0.8442",
        "region box block 0 8 0 8 0 8",
        "create_box 1 box",
        "create_atoms 1 box",
        "mass 1 1.0",
        "pair_style lj/cut 2.5",
        "pair_coeff 1 1 1.0 1.0 2.5",
        "neighbor 0.3 bin",
        "neigh_modify every 1 delay 0 check yes",
        "velocity all create 1.0 87287 mom yes rot yes dist gaussian",
        "min_style fire",
        "minimize 1.0e-8 1.0e-8 1000 10000",
        "reset_timestep 0",
        f"dump traj all custom 10 {trajectory_path.name} id type x y z vx vy vz",
        "dump_modify traj sort id",
        "thermo 25",
        "thermo_style custom step temp pe etotal press",
        "fix thermostat all nvt temp 1.0 1.0 1.0",
        "run 250",
        "unfix thermostat",
        "undump traj",
    ]

    lmp = lammps(cmdargs=cmdargs)
    try:
        for command in commands:
            lmp.command(command)
    finally:
        lmp.close()

    return {
        "trajectory_path": str(trajectory_path.resolve()),
        "natoms": int(lmp.get_natoms()),
        "trajectory_file": trajectory_path.name,
    }


@pipe.chore(name="analyze_with_ovito", num_tasks=1, cores_per_task=1)
def analyze_with_ovito(simulation: dict) -> dict:
    """Analyze the trajectory with a standalone OVITO Python script."""

    workdir = Path.cwd()
    trajectory_path = Path(simulation["trajectory_path"]).resolve()
    analysis_script = workdir / "ovito_analysis.py"
    coordination_csv = workdir / "coordination_over_time.csv"
    rendered_image = workdir / "ovito_frame.png"

    analysis_script.write_text(textwrap.dedent("""
            from __future__ import annotations

            import csv
            import sys
            from pathlib import Path

            from ovito.data import CutoffNeighborFinder
            from ovito.io import import_file
            from ovito.vis import TachyonRenderer, Viewport


            def main() -> None:
                input_path = Path(sys.argv[1])
                csv_path = Path(sys.argv[2])
                image_path = Path(sys.argv[3])

                pipeline = import_file(str(input_path))
                cutoff = 1.5

                rows = []
                for frame in range(pipeline.source.num_frames):
                    data = pipeline.compute(frame)
                    timestep = int(data.attributes.get("Timestep", frame))
                    finder = CutoffNeighborFinder(cutoff, data)
                    positions = data.particles.positions
                    particle_ids = range(1, data.particles.count + 1)
                    coordination = []

                    for particle_index, _position in enumerate(positions):
                        neighbor_count = sum(1 for _ in finder.find(particle_index))
                        coordination.append(neighbor_count)

                    for particle_id, coordination_number in zip(particle_ids, coordination):
                        rows.append(
                            (
                                frame,
                                timestep,
                                int(particle_id),
                                float(coordination_number),
                            )
                        )

                with csv_path.open("w", newline="") as handle:
                    writer = csv.writer(handle)
                    writer.writerow(["frame", "timestep", "particle_id", "coordination"])
                    writer.writerows(rows)

                final_frame = max(0, pipeline.source.num_frames - 1)
                pipeline.add_to_scene()

                viewport = Viewport(type=Viewport.Type.Perspective)
                viewport.camera_pos = (18.0, 18.0, 18.0)
                viewport.camera_dir = (-1.0, -1.0, -1.0)
                viewport.fov = 45.0
                viewport.render_image(
                    filename=str(image_path),
                    size=(1200, 900),
                    frame=final_frame,
                    renderer=TachyonRenderer(),
                )


            if __name__ == "__main__":
                main()
            """).strip() + "\n")

    subprocess.run(
        [
            sys.executable,
            str(analysis_script),
            str(trajectory_path),
            str(coordination_csv),
            str(rendered_image),
        ],
        check=True,
    )

    return {
        "trajectory_path": str(trajectory_path),
        "coordination_csv": str(coordination_csv),
        "rendered_image": str(rendered_image),
    }


simulation = run_lammps_lj_nvt()
analysis = analyze_with_ovito(simulation)

future = pipe.submit(log_delay=5, dashboard=False)
print(future.result())
