#!/usr/bin/env bash

# Generated by MatEnsemble MCP.
# System: perlmutter
# Campaign: lammps_ovito_coordination_perlmutter_2026-06-11
# Source template: example_workflows/perlmutter/<selected>/run_batch.slurm

#SBATCH -A m5014_g
#SBATCH -J lammps_ovito_coordination_perlmu
#SBATCH -o launch_logs/%x-%j.out
#SBATCH -e launch_logs/%x-%j.err
#SBATCH -t 00:30:00
#SBATCH -N 2
#SBATCH --qos debug
#SBATCH -C gpu
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4

matensemble set-image ghcr.io/q-cad/matensemble:perlmutter-v0.3.11
matensemble run workflow.py
