FROM ghcr.io/q-cad/matensemble-base:linux

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

# clone MatEnsemble
RUN git clone --depth 1 https://github.com/Q-CAD/MatEnsemble.git matensemble && \
    cd matensemble 						                               && \
    uv export --format requirements.txt --output-file requirements.txt && \
    uv pip install -r requirements.txt				                   && \
    uv pip install jupyter ipykernel

ENV PATH="/opt/basic/bin:${PATH}"
