FROM ghcr.io/freddude2004/matensemble-base:linux

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    mesa-utils \
    libgl1-mesa-dri \
    libosmesa6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Clone and install MatEnsemble
WORKDIR /opt
RUN git clone --depth 1 https://github.com/FredDude2004/MatEnsemble.git matensemble && \
    cd matensemble 				     && \
    uv pip install -e .              && \
    uv pip install jupyter ipykernel

ENV PATH="/opt/basic/bin:${PATH}"
